### ISSUE TITLE
App components not rendering on the browser

### ISSUE THREAD

**Issue by mehtavishwa30** [gladchinda/realtime-visualization-react-demo#2]
The web app is unable to render components in the browser.
The warning says an element is deprecated.

![Screen Shot 2019-04-25 at 11 13 05 PM](https://user-images.githubusercontent.com/32997409/56756843-55a08900-67b0-11e9-8399-d839c4f2d140.png)

Further in the inspector window, the console shows a message that the Element.createShadowRoot is deprecated and no longer conforms with M73 standards in 2019. 

Is the app having issues loading components because of the element? Or is it something else?

**Comment by gladchinda** [comment]
Hello @mehtavishwa30. The app renders correctly on my browser. Please provide more context, like:
- what browser and version are you using?
- what components are not loading?

The `Element.createShadowRoot()` warning is most likely from one of the app's dependencies, since the feature has been deprecated in favor of `Element.attachShadow()`.

**Comment by mehtavishwa30** [comment]
Hi @gladchinda 
I am using Chrome Version 73.0.3683.86.
On running the app the index page on the browser remains blank except just the separator.

This is what's going on in the terminal:

![Screen Shot 2019-04-26 at 1 30 19 PM](https://user-images.githubusercontent.com/32997409/56792632-a4d5d080-6827-11e9-9b78-42d039acc0e0.png)

This is how the browser tab looks like:

![Screen Shot 2019-04-26 at 1 31 31 PM](https://user-images.githubusercontent.com/32997409/56792652-ae5f3880-6827-11e9-85de-56d3eb14e7d9.png)

**Comment by gladchinda** [comment]
Hello @mehtavishwa30

I'm using the exact same version of Chrome on my PC and everything is loading just right. Are you sure you have your Pusher credentials properly setup in the app's `.env` file? Since that could be a possible reason why the application may fail to load.

Add a `.env` file to the root of your project with the following content (as specified in the README of this project):

```ini
PUSHER_APP_ID=<YOUR_PUSHER_APP_ID>
PUSHER_APP_KEY=<YOUR_PUSHER_APP_KEY>
PUSHER_APP_SECRET=<YOUR_PUSHER_APP_SECRET>
PUSHER_APP_CLUSTER=<YOUR_PUSHER_APP_CLUSTER>
```

Replace the _`<pusher credentials>`_ with what you already have setup for your Pusher application. First create a Pusher application if you don't have one already.

**Comment by mehtavishwa30** [comment]
Hi @gladchinda,

Yes! So it was the Pusher credentials all along. I have no idea why even after double checking them a couple of times, it did not work. I finally created another set of credentials on my Pusher dashboard and added them to the file. Works just fine now.

Thanks!
